init-array2.c(1)[13..14]: error: attempting to initialize 'array[5]int' with 'int'
init-array2.c(3)[30..31]: warning: excess elements in 'array[5]int' initializer
init-array2.c(4)[18..19]: warning: excess elements in scalar initializer
init-array2.c(6)[16..18]: error: negative designator index
init-array2.c(7)[15..18]: error: array designator index (8) exceeds array bounds (5)
init-array2.c(8)[15..18]: error: array designator index (5) exceeds array bounds (5)
