init-scalar1.c(5)[10..16]: warning: too many braces around scalar initializer
init-scalar1.c(7)[10..18]: warning: too many braces around scalar initializer
init-scalar1.c(7)[11..17]: warning: too many braces around scalar initializer
init-scalar1.c(9)[15..17]: warning: excess elements in scalar initializer
init-scalar1.c(11)[11..15]: warning: too many braces around scalar initializer
init-scalar1.c(11)[16..18]: warning: excess elements in scalar initializer
init-scalar1.c(13)[13..20]: warning: too many braces around scalar initializer
init-scalar1.c(13)[17..19]: warning: excess elements in scalar initializer
init-scalar1.c(13)[21..23]: warning: excess elements in scalar initializer
init-scalar1.c(15)[10..12]: error: empty scalar initializer
init-scalar1.c(19)[24..27]: warning: too many braces around scalar initializer
