decl7.c(3)[12..20]: error: function returning an array
decl7.c(6)[13..17]: error: array of functions
decl7.c(8)[13..21]: error: function returning a function
decl7.c(10)[13..21]: error: function returning a function
decl7.c(17)[10..15]: error: field declared as a function in struct/union
decl7.c(17)[10..15]: error: 'func1' has an incomplete type
decl7.c(20)[13..14]: error: syntax error, unexpected [, expecting ( or )
