decl2.c(7)[1..20]: error: More than one 'signed' specified
decl2.c(8)[1..25]: error: More than one 'unsigned' specified
decl2.c(9)[8..16]: error: Both 'unsigned' and 'signed' specified
decl2.c(10)[1..27]: error: More than one '_Thread_local' specified
decl2.c(11)[1..27]: error: More than one '_Complex' specified
decl2.c(12)[1..29]: error: More than one '_Imaginary' specified
decl2.c(13)[1..22]: error: More than one 'typedef' specified
decl2.c(14)[9..16]: error: More than one 'typedef' specified
decl2.c(14)[17..24]: error: More than one 'typedef' specified
decl2.c(15)[1..20]: error: More than one 'extern' specified
decl2.c(16)[1..20]: error: More than one 'static' specified
decl2.c(20)[3..21]: error: More than one 'auto' specified
decl2.c(21)[3..25]: error: More than one 'register' specified
decl2.c(24)[9..15]: error: Both 'extern' and 'typedef' specified
decl2.c(25)[8..14]: error: Both 'static' and 'extern' specified
decl2.c(26)[8..14]: error: Both 'static' and 'extern' specified
decl2.c(26)[15..19]: error: Both 'auto' and 'extern' specified
decl2.c(28)[1..16]: error: More than one '_Bool' specified
decl2.c(29)[1..15]: error: More than one 'char' specified
decl2.c(30)[1..15]: error: More than one 'int' specified
decl2.c(31)[1..17]: error: More than one 'void' specified
decl2.c(32)[1..17]: error: More than one 'float' specified
decl2.c(33)[1..18]: error: More than one 'double' specified
decl2.c(34)[7..10]: error: Both 'int' and '_Bool' specified
decl2.c(35)[5..9]: error: Both 'char' and 'int' specified
decl2.c(36)[7..10]: error: Both 'int' and 'float' specified
decl2.c(37)[5..10]: error: Both 'float' and 'int' specified
decl2.c(37)[11..15]: error: Both 'char' and 'int' specified
decl2.c(41)[1..21]: error: More than one 'struct S1' specified
decl2.c(42)[17..19]: error: Both 'union S2' and 'struct S1' specified
decl2.c(46)[7..12]: error: More than one 'short' specified
decl2.c(47)[7..11]: error: Both 'long' and 'short' specified
decl2.c(50)[11..15]: error: Both 'long' and 'long long' specified
decl2.c(51)[6..11]: error: Both 'short' and 'long' specified
decl2.c(52)[7..11]: error: Both 'long' and 'short' specified
decl2.c(52)[12..16]: error: Both 'long' and 'short' specified
decl2.c(53)[11..16]: error: Both 'short' and 'long long' specified
decl2.c(55)[1..9]: warning: implicit 'double' assumed with '_Complex'
decl2.c(56)[1..7]: warning: implicit 'int' assumed
decl2.c(61)[1..15]: error: Both 'signed' and '_Bool' specified
decl2.c(61)[1..15]: error: Both 'unsigned' and '_Bool' specified
decl2.c(61)[1..15]: error: Both 'short' and '_Bool' specified
decl2.c(61)[1..15]: error: Both 'long' and '_Bool' specified
decl2.c(62)[1..16]: error: Both 'signed' and 'void' specified
decl2.c(62)[1..16]: error: Both 'unsigned' and 'void' specified
decl2.c(62)[1..16]: error: Both 'short' and 'void' specified
decl2.c(62)[1..16]: error: Both 'long' and 'void' specified
decl2.c(63)[1..15]: error: Both 'signed' and 'float' specified
decl2.c(63)[1..15]: error: Both 'unsigned' and 'float' specified
decl2.c(63)[1..15]: error: Both 'short' and 'float' specified
decl2.c(63)[1..15]: error: Both 'long' and 'float' specified
decl2.c(64)[1..16]: error: Both 'signed' and 'double' specified
decl2.c(64)[1..16]: error: Both 'unsigned' and 'double' specified
decl2.c(64)[1..16]: error: Both 'short' and 'double' specified
decl2.c(65)[1..19]: error: Both 'signed' and 'struct S3' specified
decl2.c(65)[1..19]: error: Both 'unsigned' and 'struct S3' specified
decl2.c(65)[1..19]: error: Both 'short' and 'struct S3' specified
decl2.c(65)[1..19]: error: Both 'long' and 'struct S3' specified
decl2.c(66)[1..18]: error: Both 'signed' and 'union S4' specified
decl2.c(66)[1..18]: error: Both 'unsigned' and 'union S4' specified
decl2.c(66)[1..18]: error: Both 'short' and 'union S4' specified
decl2.c(66)[1..18]: error: Both 'long' and 'union S4' specified
decl2.c(67)[1..14]: error: Both 'short' and 'char' specified
decl2.c(67)[1..14]: error: Both 'long' and 'char' specified
