decl3.c(4)[8..13]: error: type qualifiers in non-parameter array declarator
decl3.c(5)[8..14]: error: 'static' in non-parameter array declarator
decl3.c(6)[8..9]: error: '[*]' in non-parameter array declarator
decl3.c(14)[10..15]: error: type qualifiers in non-parameter array declarator
decl3.c(15)[10..16]: error: 'static' in non-parameter array declarator
decl3.c(16)[10..11]: error: '[*]' in non-parameter array declarator
decl3.c(20)[20..21]: error: parameter 'a' already declared here: decl3.c(20)[14..15]
