decl4.c(4)[1..9]: error: 'register' storage class at file scope
decl4.c(5)[1..5]: error: 'auto' storage class at file scope
decl4.c(7)[12..14]: warning: 'v4': ignoring 'extern' in initialization
decl4.c(12)[14..16]: error: 'v6': 'extern' and initialization
decl4.c(16)[3..11]: warning: implicit 'int' assumed
decl4.c(16)[3..11]: warning: 'register' storage class is ignored
decl4.c(17)[3..7]: error: 'auto' storage class in function declaration
decl4.c(18)[3..9]: error: 'static' storage class in function declaration
decl4.c(24)[3..9]: error: storage class in struct/union scope
decl4.c(25)[7..9]: error: 'f3' has an incomplete type
decl4.c(29)[6..8]: error: 'v7' redeclared differently; previous declaration here: decl4.c(28)[5..7]
decl4.c(33)[20..22]: error: 'v8' redeclared differently; previous declaration here: decl4.c(31)[14..16]
decl4.c(38)[5..7]: error: 'v9': invalid redefinition; already defined here: decl4.c(37)[5..7]
decl4.c(40)[12..14]: error: 'v9': invalid redeclaration; previously declared here: decl4.c(37)[5..7]
decl4.c(46)[15..18]: error: 'v10' redeclared differently; previous declaration here: decl4.c(42)[5..8]
decl4.c(53)[7..10]: error: 'v11': invalid redeclaration; previously declared here: decl4.c(52)[14..17]
decl4.c(57)[12..15]: error: 'v12': invalid redeclaration; previously declared here: decl4.c(56)[5..8]
