decl6.c(4)[19..20]: warning: declaration of 'union X' will not be visible outside of the function
decl6.c(6)[20..21]: warning: declaration of 'union X' will not be visible outside of the function
decl6.c(6)[43..44]: error: 'struct X' previously defined as a different kind of tag here: decl6.c(6)[20..21]
decl6.c(6)[43..44]: warning: declaration of 'struct' will not be visible outside of the function
decl6.c(16)[21..23]: warning: declaration of 'struct SS' will not be visible outside of the function
decl6.c(20)[21..23]: warning: declaration of 'struct S5' will not be visible outside of the function
