pp-const-1.c(2)[1..5]: warning: Multi-character character constant
pp-const-1.c(3)[1..8]: error: Character constant is too long for its type
pp-const-1.c(4)[1]..(5)[5]: error: Character constant is too long for its type
pp-const-1.c(7)[1..4]: error: Unterminated character constant
pp-const-1.c(7)[1..4]: warning: Multi-character character constant
pp-const-1.c(8)[1..5]: warning: Multi-character character constant
pp-const-1.c(9)[1..86]: error: Character constant is too long for its type
pp-const-1.c(11)[2..5]: error: Invalid hex escape sequence in character constant
pp-const-1.c(12)[4..9]: error: Integer overflow in character constant
pp-const-1.c(12)[1..11]: warning: Multi-character character constant
pp-const-1.c(13)[3..6]: error: Character overflow in character constant
pp-const-1.c(14)[2..4]: error: Invalid escape sequence in character constant
