pp-def-1.c(3)[9..18]: warning: redefinition of macro 'MAX_COUNT' differs from previous definition at pp-def-1.c(2)[9..18]
pp-def-1.c(5)[14]..(6)[1]: error: Missing closing ')' in macro parameter list
pp-def-1.c(6)[14..15]: error: Macro parameter name expected
pp-def-1.c(7)[16]..(8)[1]: error: Missing closing ')' in macro parameter list
pp-def-1.c(8)[17]..(9)[1]: error: Expected ')' after '...' in macro parameter list
pp-def-1.c(9)[16..17]: error: Duplicated macro parameter 'a'
pp-def-1.c(12)[14..16]: error: '##' can only occur between two tokens
pp-def-1.c(13)[16..18]: error: '##' can only occur between two tokens
pp-def-1.c(16)[16..17]: error: '#' must be followed by a macro parameter
pp-def-1.c(19)[18..29]: error: '__VA_ARGS__' must only appear in a variadic macro
