pp-undef-1.c(1)[7]..(2)[1]: error: An identifier macro name expected after #undef
pp-undef-1.c(2)[8]: error: An identifier macro name expected after #undef
pp-undef-1.c(3)[8..11]: warning: Macro 'xxx' not defined in #undef
pp-undef-1.c(4)[8..11]: warning: Macro 'xxx' not defined in #undef
pp-undef-1.c(4)[12]: error: Extra tokens afer end of #undef
pp-undef-1.c(10)[8..10]: warning: Macro 'MM' not defined in #undef
